[package]
name = "unid"
version ="0.1.3"
authors = [ "UNiD <>" ]
edition = "2018"
license-file = "LICENSE"
description = "Automate device security provisioning with edge intelligence."
homepage = "https://www.getunid.io"
documentation = "https://docs.getunid.io"
repository = "https://github.com/getunid/unid"
readme = "README.md"
keywords = [
  "iot",
  "embedded",
  "root-of-trust",
  "did",
  "no_std",
]
categories = [
  "hardware-support",
  "external-ffi-bindings",
  "embedded",
  "cryptography",
  "no-std",
]
include = [
  "**/*.rs",
  "/bindings/**/*.c",
  "/bindings/**/*.h",
  "/bindings/**/*.json",
  "/Cargo.toml",
  "/Cargo.lock",
  "/CHANGELOG.md",
  "/LICENSE",
  "/README.md",
  "/SECURITY.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "unid"
crate-type = ["staticlib"]

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
linked_list_allocator = "0.9.1"
data-encoding = { version = "2.3.2", default-features = false, features = ["alloc"] }
base64 = { version = "0.13.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.9.8", default-features = false }
hmac = { version = "0.11.0", default-features = false }
cstr_core = "0.2.4"
libc = { version = "0.2.107", default-features = false }
serde_json = { version = "1.0.71", default-features = false, features = ["alloc"] }
spin = { version = "0.9.2", default-features = false, features = ["mutex", "spin_mutex"] }
scrypt = { version = "0.8.0", default-features = false, features = ["simple"] }

[profile.dev]
panic = "abort"
debug = true

[profile.test]
panic = "abort"
opt-level = 3
debug = true

[profile.release]
panic = "abort"
