name: docs
inputs:
  GITHUB_TOKEN:
    required: true
  CARGO_REGISTRY_TOKEN:
    required: true
env:
  GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
  CARGO_REGISTRY_TOKEN: ${{ inputs.CARGO_REGISTRY_TOKEN }}
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (setup) environment
      uses: ./.github/actions/shared

    - name: (docs) rustdoc
      shell: bash
      run: cargo doc
    - name: (docs) doxygen
      uses: mattnotmitt/doxygen-action@v1
