name: release
inputs:
  github-token:
    required: true
  cargo-registry-token:
    required: true
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (setup) environment
      uses: ./.github/actions/shared

    - name: (install) yarn
      shell: bash
      run: yarn
    - name: (install) rustc-dev
      shell: bash
      run: rustup component add rustc-dev
    - name: (install) semantic-release-rust
      shell: bash
      run: cargo install semantic-release-rust --version 1.0.0-alpha.8

    - name: (run) set to bump-up mode
      shell: bash
      run: mv ".releaserc_bump_up.json" ".releaserc.json"

    - name: (run) bump-up
      shell: bash
      run: |
        yarn run semantic-release

        [[ -f "VERSION" ]] && {
          semantic-release-rust prepare "$(cat VERSION)"
        } || :

    - name: (run) commit files
      shell: bash
      run: |
        [[ -f "VERSION" ]] && {
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name  "${GITHUB_ACTOR} [bot]"
          git add Cargo.*
          git commit -m "build: bump up to $(cat VERSION)"
        } || :

    - name: (run) push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github-token }}
        branch: ${{ github.ref }}

    - name: (run) restore mode
      shell: bash
      run: mv ".releaserc.json" ".releaserc_bump_up.json"
