name: release
inputs:
  GITHUB_TOKEN:
    required: true
  CARGO_REGISTRY_TOKEN:
    required: true
env:
  GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
  CARGO_REGISTRY_TOKEN: ${{ inputs.CARGO_REGISTRY_TOKEN }}
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (setup) environment
      uses: ./.github/actions/shared

    - name: (install) yarn
      shell: bash
      run: yarn

    - name: (install) rustc-dev
      shell: bash
      run: rustup component add rustc-dev
    - name: (install) semantic-release-rust
      shell: bash
      run: cargo install semantic-release-rust --version 1.0.0-alpha.8

    - name: (run) release
      shell: bash
      run: yarn run semantic-release
