name: prepare
inputs:
  GITHUB_TOKEN:
    required: true
  CARGO_REGISTRY_TOKEN:
    required: true
env:
  GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
  CARGO_REGISTRY_TOKEN: ${{ inputs.CARGO_REGISTRY_TOKEN }}
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (check) conventional commits
      uses: webiny/action-conventional-commits@v1.0.3
