name: release-pipeline

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (run) prepare
      uses: ./.github/actions/prepare

  build:
    runs-on: ubuntu-latest
    needs: [ prepare ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (run) build
      uses: ./.github/actions/build

  test:
    runs-on: ubuntu-latest
    needs: [ prepare ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (run) test
      uses: ./.github/actions/test

  docs:
    runs-on: ubuntu-latest
    needs: [ build, test ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (run) docs
      uses: ./.github/actions/docs

  release:
    runs-on: ubuntu-latest
    needs: [ docs ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v2
    - name: (run) release
      uses: ./.github/actions/release
